import { useEffect, useState } from 'react'
import { translations, type Language } from './localization'
import './App.css'

const GITHUB_URL = 'https://github.com/AG-Pixel-creater/AG-Price-Scope-Website-'
const featureIcons = ['↗', '≋', '∿', '↓', '↔', '◇', '▤', '⌕', '文', '◐']
const reportLabels = ['Product', 'Search Results', 'Lowest Observed Price', 'Average Price', 'Highest Observed Price', 'Price Range', 'Platforms Found', 'Alternative Options']

function App() {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('agps-language') as Language) || 'ur')
  const [theme, setTheme] = useState<'dark' | 'light'>(() => (localStorage.getItem('agps-theme') as 'dark' | 'light') || 'dark')
  const [menuOpen, setMenuOpen] = useState(false)
  const copy = translations[language]
  const urdu = language === 'ur'
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = urdu ? 'rtl' : 'ltr'; localStorage.setItem('agps-language', language) }, [language, urdu])
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('agps-theme', theme) }, [theme])
  const jump = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }) }
  const nav = [['home', copy.nav.home], ['features', copy.nav.features], ['process', copy.nav.process], ['report', copy.nav.report], ['download', copy.nav.download], ['docs', copy.nav.docs]]
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="#home"><span className="brand-mark">AG</span><span><strong>AG Price</strong><small>Scope</small></span></a><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'} aria-label="Primary navigation">{nav.map(([id, label]) => <button key={id} onClick={() => jump(id)}>{label}</button>)}</nav><div className="top-actions"><button className="icon-button" aria-label={copy.ui.theme} onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? '☼' : '◐'}</button><button className="language-button" onClick={() => setLanguage(urdu ? 'en' : 'ur')}><span>文</span>{copy.ui.language}</button><button className="menu-button" aria-label={menuOpen ? copy.ui.close : copy.ui.menu} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? '×' : '☰'}</button></div></header>
    <main>
      <section id="home" className="hero section-pad"><div className="hero-copy"><span className="eyebrow">{copy.hero.eyebrow}</span><h1>{copy.hero.title}</h1><p className="hero-body">{copy.hero.body}</p><div className="hero-actions"><button className="button button-primary" onClick={() => jump('download')}>{copy.hero.primary}<span>↗</span></button><button className="button button-quiet" onClick={() => jump('process')}>{copy.hero.secondary}<span>↓</span></button></div><div className="release-line"><span className="status-dot" />{copy.hero.version}<i />{copy.hero.platform}</div></div><div className="hero-visual"><div className="orbital orbital-one" /><div className="orbital orbital-two" /><div className="preview-window"><div className="window-bar"><span className="window-brand"><span className="mini-mark">AG</span> Price Scope</span><span className="window-dots">•••</span></div><div className="preview-content"><div className="preview-heading"><span>{urdu ? 'قیمت تجزیہ' : 'Price analysis'}</span><b>•••</b></div><div className="mock-product"><span className="product-icon">▦</span><div><strong>NVIDIA RTX 5090</strong><small>{urdu ? 'تلاش مکمل' : 'Search complete'}</small></div><span className="check">✓</span></div><div className="mini-stats"><span><small>{urdu ? 'کم' : 'Lowest'}</small><b>—</b></span><span><small>{urdu ? 'اوسط' : 'Average'}</small><b>—</b></span><span><small>{urdu ? 'نتائج' : 'Results'}</small><b>—</b></span></div><div className="chart"><span className="chart-line" /><span className="chart-fill" /></div><div className="mock-rows"><span /><span /><span /></div></div></div></div></section>
      <div className="trust-strip"><span>{copy.trust}</span><span className="strip-line" /><span>AG PIXEL CREATER</span></div>
      <section id="process" className="section-pad"><div className="section-intro"><span className="eyebrow">{copy.process.kicker}</span><h2>{copy.process.title}</h2><p>{copy.process.body}</p></div><div className="process-grid">{copy.process.steps.map((step, i) => <article className={`process-card ${i === 0 ? 'active' : ''}`} key={step.n}><span className="step-number">{step.n}</span><h3>{step.title}</h3><p>{step.body}</p>{step.n === '01' && <code>NVIDIA RTX 5090</code>}<span className="step-arrow">{i === 3 ? '↗' : '→'}</span></article>)}</div></section>
      <section id="features" className="section-pad feature-section"><div className="section-intro centered"><span className="eyebrow">{copy.features.kicker}</span><h2>{copy.features.title}</h2><p>{copy.features.body}</p></div><div className="feature-grid">{copy.features.items.map((item, i) => { const [title, body] = item.split('|'); return <article className="feature-card" key={title}><span className="feature-icon">{featureIcons[i]}</span><h3>{title}</h3><p>{body}</p></article> })}</div></section>
      <section id="report" className="section-pad analysis-section"><div className="section-intro"><span className="eyebrow">{copy.analysis.kicker}</span><h2>{copy.analysis.title}</h2><p>{copy.analysis.body}</p></div><div className="analysis-mock"><div className="mock-top"><div><span className="mock-label">{copy.analysis.mock}</span><h3>{copy.analysis.product}</h3></div><span className="mock-filter">⌕ {urdu ? 'تلاش' : 'Search'}</span></div><div className="stats-row">{(urdu ? ['کم قیمت', 'اوسط قیمت', 'زیادہ قیمت', 'نتائج'] : ['Lowest Price', 'Average Price', 'Highest Price', 'Results']).map(label => <div className="stat-card" key={label}><small>{label}</small><strong>—</strong></div>)}</div><div className="comparison-table"><div className="table-row table-head"><span>{urdu ? 'پلیٹ فارم' : 'Platform'}</span><span>{urdu ? 'پروڈکٹ' : 'Product'}</span><span>{urdu ? 'قیمت' : 'Price'}</span><span>{urdu ? 'دستیابی' : 'Availability'}</span></div>{['Platform A', 'Platform B', 'Platform C'].map(platform => <div className="table-row" key={platform}><span><i className="platform-dot" />{platform}</span><span>RTX 5090</span><span>—</span><span>—</span></div>)}</div></div></section>
      <section className="section-pad report-section"><div className="report-card"><div className="report-copy"><span className="eyebrow">{copy.report.kicker}</span><h2>{copy.report.title}</h2><p>{copy.report.body}</p></div><div className="report-sheet"><div className="sheet-head"><span className="sheet-icon">▤</span><div><small>AG PRICE SCOPE</small><strong>{urdu ? 'قیمت تجزیہ رپورٹ' : 'Price analysis report'}</strong></div><span className="sheet-code">0.0.1</span></div>{reportLabels.map((label, i) => <div className="report-line" key={label}><span>{urdu ? ['پروڈکٹ', 'Search Results', 'کم دیکھی گئی قیمت', 'اوسط قیمت', 'زیادہ دیکھی گئی قیمت', 'قیمت کا فرق', 'ملنے والے پلیٹ فارمز', 'متبادل آپشنز'][i] : label}</span><b>{i === 0 ? 'NVIDIA RTX 5090' : '—'}</b></div>)}</div></div></section>
      <section id="download" className="section-pad download-section"><div className="download-inner"><span className="eyebrow">{copy.download.kicker}</span><h2>{copy.download.title}</h2><p>{copy.download.body}</p><div className="download-meta"><span><small>{urdu ? 'ورژن' : 'Version'}</small><b>0.0.1</b></span><span><small>{urdu ? 'پلیٹ فارم' : 'Platform'}</small><b>Windows</b></span><span><small>{urdu ? 'ایپلیکیشن' : 'Application'}</small><b>AG Price Scope</b></span></div><button className="button disabled-button" disabled>{copy.download.button}<span>↓</span></button><small className="download-note">{copy.download.unavailable}</small></div></section>
      <section className="section-pad"><div className="section-intro"><span className="eyebrow">{copy.docs.kicker}</span><h2>{copy.install.title}</h2></div><div className="install-layout"><ol className="install-steps">{copy.install.steps.map((step, i) => <li key={step}><span>0{i + 1}</span><p>{step}</p></li>)}</ol><div className="trouble-box"><span className="feature-icon">!</span><div><h3>{copy.install.trouble}</h3><p>{copy.install.troubleBody}</p></div></div></div></section>
      <section id="docs" className="section-pad docs-section"><div className="section-intro centered"><span className="eyebrow">{copy.docs.kicker}</span><h2>{copy.docs.title}</h2></div><div className="docs-grid">{copy.docs.sections.map(section => { const [title, body] = section.split('|'); return <article key={title}><span className="doc-mark">/</span><h3>{title}</h3><p>{body}</p></article> })}</div><div className="requirements"><h3>{copy.requirements.title}</h3><div><span><small>{copy.requirements.os}</small><b>{copy.requirements.osValue}</b></span><span><small>{copy.requirements.version}</small><b>{copy.requirements.versionValue}</b></span></div></div></section>
    </main>
    <footer className="footer"><div className="footer-brand"><a className="brand" href="#home"><span className="brand-mark">AG</span><span><strong>AG Price</strong><small>Scope</small></span></a><p>{copy.footer.body}</p></div><div className="footer-links"><div><a href="#home">{copy.nav.home}</a><a href="#features">{copy.nav.features}</a><a href="#download">{copy.nav.download}</a><a href="#docs">{copy.nav.docs}</a></div><a className="github-link" href={GITHUB_URL} target="_blank" rel="noreferrer">{copy.footer.github} ↗</a></div><div className="footer-bottom"><span>{copy.footer.copyright}</span><span>AG Price Scope · 0.0.1</span></div></footer>
  </div>
}
export default App
