export type Language = 'ur' | 'en'

export const translations = {
  ur: {
    nav: { home: 'ہوم', features: 'خصوصیات', process: 'کیسے کام کرتا ہے', report: 'رپورٹ', download: 'ڈاؤن لوڈ', docs: 'دستاویزات' },
    ui: { language: 'English', theme: 'تھیم تبدیل کریں', menu: 'مینو کھولیں', close: 'مینو بند کریں' },
    hero: { eyebrow: 'آپ کی قیمت تحقیق، ایک جگہ', title: 'قیمتوں کو سمجھیں۔ بہتر فیصلہ کریں۔', body: 'کسی بھی پروڈکٹ کا نام دیں، دستیاب پلیٹ فارمز پر اس کی قیمتیں تلاش کریں، اوسط قیمت جانیں اور ایک مکمل Price Analysis Report حاصل کریں۔', primary: 'AG Price Scope ڈاؤن لوڈ کریں', secondary: 'طریقہ کار دیکھیں', version: 'ورژن 0.0.1', platform: 'Windows کے لیے' },
    trust: 'Windows ڈیسک ٹاپ ایپلیکیشن · قیمتیں تلاش اور تجزیہ کرنے کا آسان طریقہ',
    process: { kicker: 'سادہ عمل، واضح نتیجہ', title: 'پروڈکٹ سے رپورٹ تک', body: 'AG Price Scope دستیاب سرچ ذرائع سے حاصل شدہ نتائج کو ایک مفید، قابل فہم خلاصے میں بدلنے میں مدد دیتا ہے۔', steps: [{ n: '01', title: 'پروڈکٹ درج کریں', body: 'جس پروڈکٹ کی تحقیق کرنی ہو اس کا نام لکھیں۔', code: 'NVIDIA RTX 5090' }, { n: '02', title: 'پلیٹ فارمز تلاش کریں', body: 'ایپ دستیاب اور معاون آن لائن پلیٹ فارمز پر مماثل نتائج تلاش کرتی ہے۔' }, { n: '03', title: 'قیمتوں کا تجزیہ کریں', body: 'کم، زیادہ، اوسط قیمت اور فرق جیسی معلومات کو ایک جگہ دیکھیں۔' }, { n: '04', title: 'حتمی رپورٹ پائیں', body: 'جمع شدہ معلومات کا واضح خلاصہ رپورٹ کی صورت میں حاصل کریں۔' }] },
    features: { kicker: 'جو چیز اہم ہے', title: 'قیمت کے پیچھے کی تصویر دیکھیں', body: 'صرف ایک listing نہیں، دستیاب نتائج کا وسیع تر جائزہ لیں۔', items: ['Multi-Platform Price Search|درخواست کردہ پروڈکٹ کو معاون پلیٹ فارمز پر تلاش کریں۔', 'Price Comparison|مختلف پلیٹ فارمز پر ملنے والی قیمتوں کا موازنہ کریں۔', 'Average Price|کافی درست نتائج دستیاب ہوں تو اوسط قیمت معلوم کریں۔', 'Lowest Price|جمع شدہ نتائج میں سب سے کم دیکھی گئی قیمت شناخت کریں۔', 'Price Range|کم اور زیادہ دیکھی گئی قیمتوں کے درمیان فرق دیکھیں۔', 'Alternative Options|تلاش کے دوران ملنے والے متعلقہ متبادل نتائج دیکھیں۔', 'Final Report|تحقیق کا صاف اور مفید خلاصہ تیار کریں۔', 'Product Research|موجودہ مشاہدہ شدہ مارکیٹ قیمتوں کی وسیع تصویر پائیں۔', 'Urdu + English|ایپلیکیشن دونوں زبانوں کو سپورٹ کرتی ہے۔', 'Dark + Light Mode|اپنی پسند کا تھیم منتخب کریں۔'] },
    analysis: { kicker: 'انٹرفیس کا پیش نظارہ', title: 'تحقیق کو ایک نظر میں سمجھیں', body: 'یہ ایک illustrative UI mockup ہے۔ دکھائی گئی قیمتیں حقیقی مارکیٹ ڈیٹا نہیں ہیں۔', mock: 'UI EXAMPLE · LIVE DATA نہیں', product: 'NVIDIA RTX 5090' },
    report: { kicker: 'حتمی رپورٹ', title: 'نتائج کو فیصلے کے قابل بنائیں', body: 'اصل values ڈیسک ٹاپ ایپلیکیشن کے جمع شدہ سرچ نتائج سے تیار ہوتی ہیں۔ یہ layout صرف رپورٹ کی شکل سمجھانے کے لیے ہے۔' },
    download: { kicker: 'اب شروع کریں', title: 'AG Price Scope ڈاؤن لوڈ کریں', body: 'Windows ڈیسک ٹاپ کے لیے موجودہ ورژن حاصل کریں۔ ڈاؤن لوڈ لنک اس وقت دستیاب نہیں جب تک کوئی حقیقی release asset شائع نہ ہو۔', button: 'Windows کے لیے ڈاؤن لوڈ', unavailable: 'حقیقی release asset دستیاب ہونے پر ڈاؤن لوڈ لنک یہاں آئے گا۔' },
    docs: { kicker: 'دستاویزات', title: 'AG Price Scope کے بارے میں', sections: ['یہ کیا ہے؟|AG Price Scope ایک Windows ڈیسک ٹاپ ایپلیکیشن ہے جو آپ کے دیے گئے پروڈکٹ نام کے لیے دستیاب سرچ ذرائع سے قیمت کے نتائج جمع کرنے اور ان کا تجزیہ کرنے میں مدد دیتی ہے۔', 'بنیادی استعمال|پروڈکٹ کا نام درج کریں، دستیاب نتائج کا انتظار کریں، پھر کم، زیادہ، اوسط قیمت اور متعلقہ معلومات پر مبنی رپورٹ دیکھیں۔', 'تنصیب|installer ڈاؤن لوڈ کریں، اسے چلائیں، installation wizard مکمل کریں اور AG Price Scope لانچ کریں۔', 'سپورٹ اور رازداری|معاون پلیٹ فارمز ایپلیکیشن کے دستیاب سرچ ذرائع پر منحصر ہیں۔ ویب سائٹ ایپ کے اندرونی data handling کے بارے میں غیر دستاویزی دعوے نہیں کرتی۔'] },
    install: { title: 'چند آسان مراحل', steps: ['AG Price Scope installer ڈاؤن لوڈ کریں۔', 'installer چلائیں۔', 'installation wizard کی ہدایات پر عمل کریں۔', 'AG Price Scope لانچ کریں۔'], trouble: 'مسئلہ ہو تو', troubleBody: 'Windows کی security warning کی صورت میں صرف اسی installer کو چلائیں جو آپ نے تصدیق شدہ release source سے حاصل کیا ہو۔' },
    requirements: { title: 'بنیادی معلومات', os: 'آپریٹنگ سسٹم', osValue: 'Windows', version: 'ورژن', versionValue: '0.0.1' },
    footer: { body: 'قیمت تحقیق کو زیادہ واضح بنانے والی Windows ایپلیکیشن۔', github: 'GitHub Repository', copyright: '© AG Pixel Creater' }
  },
  en: {
    nav: { home: 'Home', features: 'Features', process: 'How It Works', report: 'Report', download: 'Download', docs: 'Documentation' },
    ui: { language: 'اردو', theme: 'Toggle theme', menu: 'Open menu', close: 'Close menu' },
    hero: { eyebrow: 'Price research, with a clearer view', title: 'Understand prices. Decide with confidence.', body: 'Search for a product across available platforms, compare observed prices, understand the average, and get a complete price analysis report.', primary: 'Download AG Price Scope', secondary: 'See how it works', version: 'Version 0.0.1', platform: 'For Windows' },
    trust: 'Windows desktop application · A clearer way to research and analyze prices',
    process: { kicker: 'A simple process, a useful result', title: 'From product to report', body: 'AG Price Scope helps turn results collected from available search sources into a useful, readable summary.', steps: [{ n: '01', title: 'Enter Product', body: 'Type the product name you want to research.', code: 'NVIDIA RTX 5090' }, { n: '02', title: 'Search Platforms', body: 'The app searches supported online platforms for matching results.' }, { n: '03', title: 'Analyze Prices', body: 'See lowest, highest, average price and price differences together.' }, { n: '04', title: 'Get Final Report', body: 'Receive a clear report summarizing the collected information.' }] },
    features: { kicker: 'The useful details', title: 'See the picture behind the price', body: 'Go beyond one listing and review the broader set of observed results.', items: ['Multi-Platform Price Search|Search the requested product across supported platforms.', 'Price Comparison|Compare prices found across different platforms.', 'Average Price|Calculate an average when enough valid results are available.', 'Lowest Price|Identify the lowest observed price in the collected results.', 'Price Range|See the difference between lower and higher observed prices.', 'Alternative Options|Review relevant alternative results found during the search.', 'Final Report|Generate a clear summary of your research.', 'Product Research|Get a broader view of currently observed market prices.', 'Urdu + English|The application supports both languages.', 'Dark + Light Mode|Choose the visual mode that suits you.'] },
    analysis: { kicker: 'Product preview', title: 'Make research easy to scan', body: 'This is an illustrative UI mockup. The prices shown are not real market data.', mock: 'UI EXAMPLE · NOT LIVE DATA', product: 'NVIDIA RTX 5090' },
    report: { kicker: 'Final report', title: 'Turn results into a decision', body: 'Actual values are generated by the desktop application from its collected search results. This layout only demonstrates the report shape.' },
    download: { kicker: 'Start here', title: 'Download AG Price Scope', body: 'Get the current Windows desktop version. A download link will appear when a real release asset is published.', button: 'Download for Windows', unavailable: 'A verified release asset is not available yet, so no installer link is presented.' },
    docs: { kicker: 'Documentation', title: 'About AG Price Scope', sections: ['What is it?|AG Price Scope is a Windows desktop application that helps collect and analyze price results from available search sources for a product name you provide.', 'Basic usage|Enter a product name, wait for available results, then review the lowest, highest, average price and related information in the report.', 'Installation|Download the installer, run it, complete the installation wizard and launch AG Price Scope.', 'Support and privacy|Supported platforms depend on the application’s available search sources. This website does not make undocumented claims about the app’s internal data handling.'] },
    install: { title: 'A few straightforward steps', steps: ['Download the AG Price Scope installer.', 'Run the installer.', 'Follow the installation wizard.', 'Launch AG Price Scope.'], trouble: 'Troubleshooting', troubleBody: 'If Windows shows a security warning, only run an installer obtained from a verified release source. This website does not provide a file until a real download asset is available.' },
    requirements: { title: 'Known details', os: 'Operating system', osValue: 'Windows', version: 'Version', versionValue: '0.0.1' },
    footer: { body: 'A Windows application for clearer price research.', github: 'GitHub Repository', copyright: '© AG Pixel Creater' }
  }
} as const

export type Copy = typeof translations.en
